# Generated by Django 3.0.8 on 2020-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_produit_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
