# Generated by Django 3.0.8 on 2020-12-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_client_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraisonadresse',
            old_name='ateAjouter',
            new_name='dateAjouter',
        ),
    ]
