# Generated by Django 3.0.8 on 2020-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_auto_20201221_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraisonadresse',
            old_name='zipcode',
            new_name='telephone',
        ),
    ]
