# Generated by Django 3.0.8 on 2020-12-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_auto_20201227_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='typee',
            field=models.CharField(default='tunique', max_length=210),
        ),
    ]
