# Generated by Django 3.0.8 on 2020-12-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_auto_20201230_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
